version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ohdsi
      - POSTGRES_PASSWORD=ohdsi
      - POSTGRES_DB=omopdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vocabularies:/vocabularies
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: postgres -c max_connections=200 -c shared_buffers=2GB
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
